---
language: c
sudo: required
services: docker
matrix:
  fast_finish: true
  include:
    - script: docker run --rm -ti centos:5 /bin/sh -c 'yum install -y wget && wget -O /dev/null http://speedtest.wdc01.softlayer.com/downloads/test10.zip'
    - script: docker run --rm -ti centos:6 /bin/sh -c 'yum install -y wget && wget -O /dev/null http://speedtest.wdc01.softlayer.com/downloads/test10.zip'
    - script: docker run --rm -ti centos:7 /bin/sh -c 'yum install -y wget && wget -O /dev/null http://speedtest.wdc01.softlayer.com/downloads/test10.zip'
